baseURL = "https://420-5v6-infrastructure.netlify.app/"
languageCode = "fr-CA"
title = "Cours sur la Conteneurisation"
theme = ["hugo-theme-learn", "reveal-hugo"]

# Pour la fonctionnalité de recherche
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
editURL = "https://github.com/420-5V6-Infrastructure-Virtuelle/conteneurisation"
globalTitle = "Supports"
[params.reveal_hugo]
custom_theme = "reveal-hugo/themes/robot-lung.css"

# [menu.shortcuts]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true